#!/bin/bash
# tary, 18:03 2018/7/24

# set -x

DEV_DIR="/dev"

[ "$#" -eq 0 -o "$1" == "-h" -o "$1" == "--help" ] && {
	echo "Usage"
	echo "  $0 tty1A,tty1B tty2A,tty2B ...";
	exit 1;
}

#display_fifo=${TMPDIR:-"/tmp"}/common_test_fifo
#display_cpuinfo='0'
display_echo=
display_result=

display_message() {
	local msg="$1$2"
	# echo $msg > $display_fifo
	echo $msg
}

field_get() {
	local delim=$1
	local line=$2
	local index=$3

	set `echo $line | tr \'$delim\' ' '`
	eval val=\$$index
	echo $val
}

connection_test() {
	local out=$1
	local in=$2
	local v
	local f

	# message hello0
	f=$(mktemp)
	cat $in > $f &
	sleep 0.5
	echo -ne "hello0\n" > $out
	sleep 0.5

	v=$(cat $f)
	kill -9 $!
	wait
	echo "Recv '$v'" >&2
	rm -f $f

	[ "$v" != "hello0" ] && { return 1; }


	# quick path
	return 0;


	# mesage world1
	f=$(mktemp)
	cat $in > $f &
	sleep 0.5
	echo -ne "world1" > $out
	sleep 0.5

	kill -9 $!
	wait
	v=$(cat $f)
	echo "Recv '$v'" >&2
	rm -f $f

	[ "$v" != "world1" ] && { return 1; }

	return 0;
}

dev_setup() {
	local dev=$1
	local baud=${2:-115200}

	stty -F $dev $baud raw -onlcr -iexten -echo -echoe -echok -echoctl -echoke
	return
}

pairs_test() {
	local da=$1
	local db=$2
	local ers="$da,$db "

	[ ! -e $da -o ! -e $db ] && {
		echo -ne "$ers"
		return 1;
	}

	dev_setup $da
	dev_setup $db

	connection_test $da $db || {
		echo -ne "$ers"
		return 1;
	}

	# return 0;

	connection_test $db $da || {
		echo -ne "$ers"
		return 1;
	}
	return 0;
}

LAST_DIR=`pwd`
error_groups=""

for i in $@; do
	deva=$DEV_DIR/$(field_get ',' $i 1)
	devb=$DEV_DIR/$(field_get ',' $i 2)
	# echo DEVA=$deva DEVB=$devb

	error_groups="${error_groups}$(pairs_test $deva $devb)"
	[ "X$error_groups" != "X" ] && {
		true # display_message $display_result "$error_groups"
	}
done

# echo "#error groups = '${error_groups}'"

[ "X$error_groups" != "X" ] && {
	display_message $display_result "$error_groups"
	# sleep 5
	exit 1;
}

echo "$0: Version TTY"
display_message $display_echo " OK"
cd $LAST_DIR
exit 0
